apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  # * Create namespace before use Service 
  namespace: ns-gitea
spec:
  ports:
    # If you have some problems exposing the service, try changing ports, probably already used
  - name: ssh
    port: 22
    targetPort: 2200
    # If you have some problems exposing the service, try changing ports, probably already used
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: gitea
  type: NodePort 
# After this use -	 minikube service gitea -n ns-gitea   		-> Used to expose gitea to your localhost / One website didn't work because is not a website, is a ssh connection to push and pull repositories
