apiVersion: v1
kind: Service
metadata:
  name: gitea
  # * Create namespace before use Service 
  namespace: n-gitea
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: gitea
  type: NodePort

