apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  # * Create namespace before use Deployment 
  namespace: n-gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - image: gitea/gitea:latest
          imagePullPolicy: IfNotPresent
          name: gitea
          ports:
            # SSH
            - containerPort: 22
              protocol: TCP
            # WEB
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1
              memory: 1000Mi
          volumeMounts:
          - mountPath: /var/tmp/gitea
            name: db-volume
      volumes:
      - name: db-volume
        hostPath:
          # directory location on host
          path: /var/tmp/gitea
