apiVersion: v1
kind: Service
metadata:
  name: gitea
  # * Create namespace before use Service 
  namespace: n-gitea
spec:
  ports:
    # If you have some problems exposing the service, try changing ports, probably already used
  - name: ssh
    port: 22
    targetPort: 22
    # If you have some problems exposing the service, try changing ports, probably already used
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: gitea
  type: NodePort
# After this use -	 minikube service gitea -n n-gitea   		-> Used to expose gitea to your localhost
